name: Deploy to Fly.io

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          cd src/client && npm ci

      - name: Run tests
        run: npm test --if-present

      - name: Build application
        run: npm run build

      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Post-deployment health check
        run: |
          sleep 30
          curl -f https://${{ secrets.FLY_APP_NAME }}.fly.dev/api/health || exit 1
        env:
          FLY_APP_NAME: ${{ secrets.FLY_APP_NAME }}
